
#define ENUM_IMGUI_WINDOW_FLAGS(name) .value(#name, ImGuiWindowFlags_##name)
#define ENUM_IMGUI_CHILD_FLAGS(name) .value(#name, ImGuiChildFlags_##name)
#define ENUM_IMGUI_ITEM_FLAGS(name) .value(#name, ImGuiItemFlags_##name)
#define ENUM_IMGUI_INPUT_TEXT_FLAGS(name) .value(#name, ImGuiInputTextFlags_##name)
#define ENUM_IMGUI_TREE_NODE_FLAGS(name) .value(#name, ImGuiTreeNodeFlags_##name)
#define ENUM_IMGUI_POPUP_FLAGS(name) .value(#name, ImGuiPopupFlags_##name)
#define ENUM_IMGUI_SELECTABLE_FLAGS(name) .value(#name, ImGuiSelectableFlags_##name)
#define ENUM_IMGUI_COMBO_FLAGS(name) .value(#name, ImGuiComboFlags_##name)
#define ENUM_IMGUI_TAB_BAR_FLAGS(name) .value(#name, ImGuiTabBarFlags_##name)
#define ENUM_IMGUI_TAB_ITEM_FLAGS(name) .value(#name, ImGuiTabItemFlags_##name)
#define ENUM_IMGUI_FOCUSED_FLAGS(name) .value(#name, ImGuiFocusedFlags_##name)
#define ENUM_IMGUI_HOVERED_FLAGS(name) .value(#name, ImGuiHoveredFlags_##name)
#define ENUM_IMGUI_DRAG_DROP_FLAGS(name) .value(#name, ImGuiDragDropFlags_##name)
#define ENUM_IMGUI_DATA_TYPE(name) .value(#name, ImGuiDataType_##name)
#define ENUM_IMGUI_DIR(name) .value(#name, ImGuiDir_##name)
#define ENUM_IMGUI_SORT_DIRECTION(name) .value(#name, ImGuiSortDirection_##name)
#define ENUM_IMGUI_KEY(name) .value(#name, ImGuiKey_##name)
#define ENUM_IMGUI_INPUT_FLAGS(name) .value(#name, ImGuiInputFlags_##name)
#define ENUM_IMGUI_CONFIG_FLAGS(name) .value(#name, ImGuiConfigFlags_##name)
#define ENUM_IMGUI_COL(name) .value(#name, ImGuiCol_##name)
#define ENUM_IMGUI_STYLE_VAR(name) .value(#name, ImGuiStyleVar_##name)
#define ENUM_IMGUI_BUTTON_FLAGS(name) .value(#name, ImGuiButtonFlags_##name)
#define ENUM_IMGUI_COLOR_EDIT_FLAGS(name) .value(#name, ImGuiColorEditFlags_##name)
#define ENUM_IMGUI_SLIDER_FLAGS(name) .value(#name, ImGuiSliderFlags_##name)
#define ENUM_IMGUI_MOUSE_BUTTON(name) .value(#name, ImGuiMouseButton_##name)
#define ENUM_IMGUI_MOUSE_CURSOR(name) .value(#name, ImGuiMouseCursor_##name)
#define ENUM_IMGUI_COND(name) .value(#name, ImGuiCond_##name)
#define ENUM_IMGUI_TABLE_FLAGS(name) .value(#name, ImGuiTableFlags_##name)
#define ENUM_IMGUI_TABLE_COLUMN_FLAGS(name) .value(#name, ImGuiTableColumnFlags_##name)
#define ENUM_IMGUI_TABLE_ROW_FLAGS(name) .value(#name, ImGuiTableRowFlags_##name)
#define ENUM_IMGUI_TABLE_BG_TARGET(name) .value(#name, ImGuiTableBgTarget_##name)
#define ENUM_IMGUI_MULTI_SELECT_FLAGS(name) .value(#name, ImGuiMultiSelectFlags_##name)
#define ENUM_IMGUI_SELECTION_REQUEST_TYPE(name) .value(#name, ImGuiSelectionRequestType_##name)
#define ENUM_IMGUI_DRAW_FLAGS(name) .value(#name, ImDrawFlags_##name)
#define ENUM_IMGUI_DRAW_LIST_FLAGS(name) .value(#name, ImDrawListFlags_##name)
#define ENUM_IMGUI_FONT_ATLAS_FLAGS(name) .value(#name, ImFontAtlasFlags_##name)

#include "imgui_bindings.h"


void bind_imgui_window_flags(py::module_& m) {
    py::enum_<ImGuiWindowFlags_>(m, "WindowFlags", py::arithmetic())
        .value("None_", ImGuiWindowFlags_None)
        ENUM_IMGUI_WINDOW_FLAGS(NoTitleBar)
        ENUM_IMGUI_WINDOW_FLAGS(NoResize)
        ENUM_IMGUI_WINDOW_FLAGS(NoMove)
        ENUM_IMGUI_WINDOW_FLAGS(NoScrollbar)
        ENUM_IMGUI_WINDOW_FLAGS(NoScrollWithMouse)
        ENUM_IMGUI_WINDOW_FLAGS(NoCollapse)
        ENUM_IMGUI_WINDOW_FLAGS(AlwaysAutoResize)
        ENUM_IMGUI_WINDOW_FLAGS(NoBackground)
        ENUM_IMGUI_WINDOW_FLAGS(NoSavedSettings)
        ENUM_IMGUI_WINDOW_FLAGS(NoMouseInputs)
        ENUM_IMGUI_WINDOW_FLAGS(MenuBar)
        ENUM_IMGUI_WINDOW_FLAGS(HorizontalScrollbar)
        ENUM_IMGUI_WINDOW_FLAGS(NoFocusOnAppearing)
        ENUM_IMGUI_WINDOW_FLAGS(NoBringToFrontOnFocus)
        ENUM_IMGUI_WINDOW_FLAGS(AlwaysVerticalScrollbar)
        ENUM_IMGUI_WINDOW_FLAGS(AlwaysHorizontalScrollbar)
        ENUM_IMGUI_WINDOW_FLAGS(NoNavInputs)
        ENUM_IMGUI_WINDOW_FLAGS(NoNavFocus)
        ENUM_IMGUI_WINDOW_FLAGS(UnsavedDocument)
        ENUM_IMGUI_WINDOW_FLAGS(NoNav)
        ENUM_IMGUI_WINDOW_FLAGS(NoDecoration)
        ENUM_IMGUI_WINDOW_FLAGS(NoInputs)
        .export_values();
}

void bind_imgui_child_flags(py::module_& m) {
    py::enum_<ImGuiChildFlags_>(m, "ChildFlags", py::arithmetic())
        .value("None_", ImGuiChildFlags_None)
        ENUM_IMGUI_CHILD_FLAGS(Borders)
        ENUM_IMGUI_CHILD_FLAGS(AlwaysUseWindowPadding)
        ENUM_IMGUI_CHILD_FLAGS(ResizeX)
        ENUM_IMGUI_CHILD_FLAGS(ResizeY)
        ENUM_IMGUI_CHILD_FLAGS(AutoResizeX)
        ENUM_IMGUI_CHILD_FLAGS(AutoResizeY)
        ENUM_IMGUI_CHILD_FLAGS(AlwaysAutoResize)
        ENUM_IMGUI_CHILD_FLAGS(FrameStyle)
        .export_values();
}

void bind_imgui_item_flags(py::module_& m) {
    py::enum_<ImGuiItemFlags_>(m, "ItemFlags", py::arithmetic())
        .value("None_", ImGuiItemFlags_None)
        ENUM_IMGUI_ITEM_FLAGS(NoTabStop)
        ENUM_IMGUI_ITEM_FLAGS(NoNav)
        ENUM_IMGUI_ITEM_FLAGS(NoNavDefaultFocus)
        ENUM_IMGUI_ITEM_FLAGS(ButtonRepeat)
        ENUM_IMGUI_ITEM_FLAGS(AutoClosePopups)
        ENUM_IMGUI_ITEM_FLAGS(AllowDuplicateId)
        .export_values();
}

void bind_imgui_input_text_flags(py::module_& m) {
    py::enum_<ImGuiInputTextFlags_>(m, "InputTextFlags", py::arithmetic())
        .value("None", ImGuiInputTextFlags_None)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CharsDecimal)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CharsHexadecimal)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CharsScientific)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CharsUppercase)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CharsNoBlank)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(AllowTabInput)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(EnterReturnsTrue)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(EscapeClearsAll)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CtrlEnterForNewLine)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(ReadOnly)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(Password)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(AlwaysOverwrite)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(AutoSelectAll)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(ParseEmptyRefVal)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(DisplayEmptyRefVal)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(NoHorizontalScroll)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(NoUndoRedo)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(ElideLeft)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackCompletion)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackHistory)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackAlways)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackCharFilter)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackResize)
        ENUM_IMGUI_INPUT_TEXT_FLAGS(CallbackEdit)
        .export_values();
}

void bind_imgui_tree_node_flags(py::module_& m) {
    py::enum_<ImGuiTreeNodeFlags_>(m, "TreeNodeFlags", py::arithmetic())
        .value("None_", ImGuiTreeNodeFlags_None)
        ENUM_IMGUI_TREE_NODE_FLAGS(Selected)
        ENUM_IMGUI_TREE_NODE_FLAGS(Framed)
        ENUM_IMGUI_TREE_NODE_FLAGS(AllowOverlap)
        ENUM_IMGUI_TREE_NODE_FLAGS(NoTreePushOnOpen)
        ENUM_IMGUI_TREE_NODE_FLAGS(NoAutoOpenOnLog)
        ENUM_IMGUI_TREE_NODE_FLAGS(DefaultOpen)
        ENUM_IMGUI_TREE_NODE_FLAGS(OpenOnDoubleClick)
        ENUM_IMGUI_TREE_NODE_FLAGS(OpenOnArrow)
        ENUM_IMGUI_TREE_NODE_FLAGS(Leaf)
        ENUM_IMGUI_TREE_NODE_FLAGS(Bullet)
        ENUM_IMGUI_TREE_NODE_FLAGS(FramePadding)
        ENUM_IMGUI_TREE_NODE_FLAGS(SpanAvailWidth)
        ENUM_IMGUI_TREE_NODE_FLAGS(SpanFullWidth)
        ENUM_IMGUI_TREE_NODE_FLAGS(SpanLabelWidth)
        ENUM_IMGUI_TREE_NODE_FLAGS(SpanAllColumns)
        ENUM_IMGUI_TREE_NODE_FLAGS(LabelSpanAllColumns)
        ENUM_IMGUI_TREE_NODE_FLAGS(NavLeftJumpsToParent)
        ENUM_IMGUI_TREE_NODE_FLAGS(CollapsingHeader)
        .export_values();
}

void bind_imgui_popup_flags(py::module_& m) {
    py::enum_<ImGuiPopupFlags_>(m, "PopupFlags", py::arithmetic())
        .value("None_", ImGuiPopupFlags_None)
        ENUM_IMGUI_POPUP_FLAGS(MouseButtonLeft)
        ENUM_IMGUI_POPUP_FLAGS(MouseButtonRight)
        ENUM_IMGUI_POPUP_FLAGS(MouseButtonMiddle)
        ENUM_IMGUI_POPUP_FLAGS(MouseButtonMask_)
        ENUM_IMGUI_POPUP_FLAGS(MouseButtonDefault_)
        ENUM_IMGUI_POPUP_FLAGS(NoReopen)
        ENUM_IMGUI_POPUP_FLAGS(NoOpenOverExistingPopup)
        ENUM_IMGUI_POPUP_FLAGS(NoOpenOverItems)
        ENUM_IMGUI_POPUP_FLAGS(AnyPopupId)
        ENUM_IMGUI_POPUP_FLAGS(AnyPopupLevel)
        ENUM_IMGUI_POPUP_FLAGS(AnyPopup)
        .export_values();
}

void bind_imgui_selectable_flags(py::module_& m) {
    py::enum_<ImGuiSelectableFlags_>(m, "SelectableFlags", py::arithmetic())
        .value("None_", ImGuiSelectableFlags_None)
        ENUM_IMGUI_SELECTABLE_FLAGS(NoAutoClosePopups)
        ENUM_IMGUI_SELECTABLE_FLAGS(SpanAllColumns)
        ENUM_IMGUI_SELECTABLE_FLAGS(AllowDoubleClick)
        ENUM_IMGUI_SELECTABLE_FLAGS(Disabled)
        ENUM_IMGUI_SELECTABLE_FLAGS(AllowOverlap)
        ENUM_IMGUI_SELECTABLE_FLAGS(Highlight)
        .export_values();
}

void bind_imgui_combo_flags(py::module_& m) {
    py::enum_<ImGuiComboFlags_>(m, "ComboFlags", py::arithmetic())
        .value("None_", ImGuiComboFlags_None)
        ENUM_IMGUI_COMBO_FLAGS(PopupAlignLeft)
        ENUM_IMGUI_COMBO_FLAGS(HeightSmall)
        ENUM_IMGUI_COMBO_FLAGS(HeightRegular)
        ENUM_IMGUI_COMBO_FLAGS(HeightLarge)
        ENUM_IMGUI_COMBO_FLAGS(HeightLargest)
        ENUM_IMGUI_COMBO_FLAGS(NoArrowButton)
        ENUM_IMGUI_COMBO_FLAGS(NoPreview)
        ENUM_IMGUI_COMBO_FLAGS(WidthFitPreview)
        ENUM_IMGUI_COMBO_FLAGS(HeightMask_)
        .export_values();
}

void bind_imgui_tab_bar_flags(py::module_& m) {
    py::enum_<ImGuiTabBarFlags_>(m, "TabBarFlags", py::arithmetic())
        .value("None_", ImGuiTabBarFlags_None)
        ENUM_IMGUI_TAB_BAR_FLAGS(Reorderable)
        ENUM_IMGUI_TAB_BAR_FLAGS(AutoSelectNewTabs)
        ENUM_IMGUI_TAB_BAR_FLAGS(TabListPopupButton)
        ENUM_IMGUI_TAB_BAR_FLAGS(NoCloseWithMiddleMouseButton)
        ENUM_IMGUI_TAB_BAR_FLAGS(NoTabListScrollingButtons)
        ENUM_IMGUI_TAB_BAR_FLAGS(NoTooltip)
        ENUM_IMGUI_TAB_BAR_FLAGS(DrawSelectedOverline)
        ENUM_IMGUI_TAB_BAR_FLAGS(FittingPolicyResizeDown)
        ENUM_IMGUI_TAB_BAR_FLAGS(FittingPolicyScroll)
        ENUM_IMGUI_TAB_BAR_FLAGS(FittingPolicyMask_)
        ENUM_IMGUI_TAB_BAR_FLAGS(FittingPolicyDefault_)
        .export_values();
}

void bind_imgui_tab_item_flags(py::module_& m) {
    py::enum_<ImGuiTabItemFlags_>(m, "TabItemFlags", py::arithmetic())
        .value("None_", ImGuiTabItemFlags_None)
        ENUM_IMGUI_TAB_ITEM_FLAGS(UnsavedDocument)
        ENUM_IMGUI_TAB_ITEM_FLAGS(SetSelected)
        ENUM_IMGUI_TAB_ITEM_FLAGS(NoCloseWithMiddleMouseButton)
        ENUM_IMGUI_TAB_ITEM_FLAGS(NoPushId)
        ENUM_IMGUI_TAB_ITEM_FLAGS(NoTooltip)
        ENUM_IMGUI_TAB_ITEM_FLAGS(NoReorder)
        ENUM_IMGUI_TAB_ITEM_FLAGS(Leading)
        ENUM_IMGUI_TAB_ITEM_FLAGS(Trailing)
        ENUM_IMGUI_TAB_ITEM_FLAGS(NoAssumedClosure)
        .export_values();
}

void bind_imgui_focused_flags(py::module_& m) {
    py::enum_<ImGuiFocusedFlags_>(m, "FocusedFlags", py::arithmetic())
        .value("None_", ImGuiFocusedFlags_None)
        ENUM_IMGUI_FOCUSED_FLAGS(ChildWindows)
        ENUM_IMGUI_FOCUSED_FLAGS(RootWindow)
        ENUM_IMGUI_FOCUSED_FLAGS(AnyWindow)
        ENUM_IMGUI_FOCUSED_FLAGS(NoPopupHierarchy)
        ENUM_IMGUI_FOCUSED_FLAGS(RootAndChildWindows)
        .export_values();
}

void bind_imgui_hovered_flags(py::module_& m) {
    py::enum_<ImGuiHoveredFlags_>(m, "HoveredFlags", py::arithmetic())
        .value("None_", ImGuiHoveredFlags_None)
        ENUM_IMGUI_HOVERED_FLAGS(ChildWindows)
        ENUM_IMGUI_HOVERED_FLAGS(RootWindow)
        ENUM_IMGUI_HOVERED_FLAGS(AnyWindow)
        ENUM_IMGUI_HOVERED_FLAGS(NoPopupHierarchy)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenBlockedByPopup)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenBlockedByActiveItem)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenOverlappedByItem)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenOverlappedByWindow)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenDisabled)
        ENUM_IMGUI_HOVERED_FLAGS(NoNavOverride)
        ENUM_IMGUI_HOVERED_FLAGS(AllowWhenOverlapped)
        ENUM_IMGUI_HOVERED_FLAGS(RectOnly)
        ENUM_IMGUI_HOVERED_FLAGS(RootAndChildWindows)
        ENUM_IMGUI_HOVERED_FLAGS(ForTooltip)
        ENUM_IMGUI_HOVERED_FLAGS(Stationary)
        ENUM_IMGUI_HOVERED_FLAGS(DelayNone)
        ENUM_IMGUI_HOVERED_FLAGS(DelayShort)
        ENUM_IMGUI_HOVERED_FLAGS(DelayNormal)
        ENUM_IMGUI_HOVERED_FLAGS(NoSharedDelay)
        .export_values();
}

void bind_imgui_drag_drop_flags(py::module_& m) {
    py::enum_<ImGuiDragDropFlags_>(m, "DragDropFlags", py::arithmetic())
        .value("None_", ImGuiDragDropFlags_None)
        ENUM_IMGUI_DRAG_DROP_FLAGS(SourceNoPreviewTooltip)
        ENUM_IMGUI_DRAG_DROP_FLAGS(SourceNoDisableHover)
        ENUM_IMGUI_DRAG_DROP_FLAGS(SourceNoHoldToOpenOthers)
        ENUM_IMGUI_DRAG_DROP_FLAGS(SourceAllowNullID)
        ENUM_IMGUI_DRAG_DROP_FLAGS(SourceExtern)
        ENUM_IMGUI_DRAG_DROP_FLAGS(PayloadAutoExpire)
        ENUM_IMGUI_DRAG_DROP_FLAGS(PayloadNoCrossContext)
        ENUM_IMGUI_DRAG_DROP_FLAGS(PayloadNoCrossProcess)
        ENUM_IMGUI_DRAG_DROP_FLAGS(AcceptBeforeDelivery)
        ENUM_IMGUI_DRAG_DROP_FLAGS(AcceptNoDrawDefaultRect)
        ENUM_IMGUI_DRAG_DROP_FLAGS(AcceptNoPreviewTooltip)
        ENUM_IMGUI_DRAG_DROP_FLAGS(AcceptPeekOnly)
        .export_values();
}

void bind_imgui_data_type(py::module_& m) {
    py::enum_<ImGuiDataType_>(m, "DataType", py::arithmetic())
        ENUM_IMGUI_DATA_TYPE(S8)
        ENUM_IMGUI_DATA_TYPE(U8)
        ENUM_IMGUI_DATA_TYPE(S16)
        ENUM_IMGUI_DATA_TYPE(U16)
        ENUM_IMGUI_DATA_TYPE(S32)
        ENUM_IMGUI_DATA_TYPE(U32)
        ENUM_IMGUI_DATA_TYPE(S64)
        ENUM_IMGUI_DATA_TYPE(U64)
        ENUM_IMGUI_DATA_TYPE(Float)
        ENUM_IMGUI_DATA_TYPE(Double)
        ENUM_IMGUI_DATA_TYPE(Bool)
        ENUM_IMGUI_DATA_TYPE(String)
        .export_values();
}

void bind_imgui_dir(py::module_& m) {
    py::enum_<ImGuiDir>(m, "Dir", py::arithmetic())
        .value("None_", ImGuiDir_None)
        ENUM_IMGUI_DIR(Left)
        ENUM_IMGUI_DIR(Right)
        ENUM_IMGUI_DIR(Up)
        ENUM_IMGUI_DIR(Down)
        .export_values();
}

void bind_imgui_sort_direction(py::module_& m) {
    py::enum_<ImGuiSortDirection>(m, "SortDirection", py::arithmetic())
        .value("None_", ImGuiSortDirection_None)
        ENUM_IMGUI_SORT_DIRECTION(Ascending)
        ENUM_IMGUI_SORT_DIRECTION(Descending)
        .export_values();
}

void bind_imgui_key(py::module_& m) {
    py::enum_<ImGuiKey>(m, "Key", py::arithmetic())
        .value("None_", ImGuiKey_None)
        ENUM_IMGUI_KEY(Tab)
        ENUM_IMGUI_KEY(LeftArrow)
        ENUM_IMGUI_KEY(RightArrow)
        ENUM_IMGUI_KEY(UpArrow)
        ENUM_IMGUI_KEY(DownArrow)
        ENUM_IMGUI_KEY(PageUp)
        ENUM_IMGUI_KEY(PageDown)
        ENUM_IMGUI_KEY(Home)
        ENUM_IMGUI_KEY(End)
        ENUM_IMGUI_KEY(Insert)
        ENUM_IMGUI_KEY(Delete)
        ENUM_IMGUI_KEY(Backspace)
        ENUM_IMGUI_KEY(Space)
        ENUM_IMGUI_KEY(Enter)
        ENUM_IMGUI_KEY(Escape)
        ENUM_IMGUI_KEY(LeftCtrl) 
        ENUM_IMGUI_KEY(LeftShift) 
        ENUM_IMGUI_KEY(LeftAlt) 
        ENUM_IMGUI_KEY(LeftSuper)
        ENUM_IMGUI_KEY(RightCtrl) 
        ENUM_IMGUI_KEY(RightShift) 
        ENUM_IMGUI_KEY(RightAlt) 
        ENUM_IMGUI_KEY(RightSuper)
        ENUM_IMGUI_KEY(Menu)
        ENUM_IMGUI_KEY(0)
        ENUM_IMGUI_KEY(1)
        ENUM_IMGUI_KEY(2)
        ENUM_IMGUI_KEY(3)
        ENUM_IMGUI_KEY(4)
        ENUM_IMGUI_KEY(5)
        ENUM_IMGUI_KEY(6)
        ENUM_IMGUI_KEY(7)
        ENUM_IMGUI_KEY(8)
        ENUM_IMGUI_KEY(9)
        ENUM_IMGUI_KEY(A)
        ENUM_IMGUI_KEY(B)
        ENUM_IMGUI_KEY(C)
        ENUM_IMGUI_KEY(D)
        ENUM_IMGUI_KEY(E)
        ENUM_IMGUI_KEY(F)
        ENUM_IMGUI_KEY(G)
        ENUM_IMGUI_KEY(H)
        ENUM_IMGUI_KEY(I)
        ENUM_IMGUI_KEY(J)
        ENUM_IMGUI_KEY(K)
        ENUM_IMGUI_KEY(L)
        ENUM_IMGUI_KEY(M)
        ENUM_IMGUI_KEY(N)
        ENUM_IMGUI_KEY(O)
        ENUM_IMGUI_KEY(P)
        ENUM_IMGUI_KEY(Q)
        ENUM_IMGUI_KEY(R)
        ENUM_IMGUI_KEY(S)
        ENUM_IMGUI_KEY(T)
        ENUM_IMGUI_KEY(U)
        ENUM_IMGUI_KEY(V)
        ENUM_IMGUI_KEY(W)
        ENUM_IMGUI_KEY(X)
        ENUM_IMGUI_KEY(Y)
        ENUM_IMGUI_KEY(Z)
        ENUM_IMGUI_KEY(F1)
        ENUM_IMGUI_KEY(F2)
        ENUM_IMGUI_KEY(F3)
        ENUM_IMGUI_KEY(F4)
        ENUM_IMGUI_KEY(F5)
        ENUM_IMGUI_KEY(F6)
        ENUM_IMGUI_KEY(F7)
        ENUM_IMGUI_KEY(F8)
        ENUM_IMGUI_KEY(F9)
        ENUM_IMGUI_KEY(F10)
        ENUM_IMGUI_KEY(F11)
        ENUM_IMGUI_KEY(F12)
        ENUM_IMGUI_KEY(F13)
        ENUM_IMGUI_KEY(F14)
        ENUM_IMGUI_KEY(F15)
        ENUM_IMGUI_KEY(F16)
        ENUM_IMGUI_KEY(F17)
        ENUM_IMGUI_KEY(F18)
        ENUM_IMGUI_KEY(F19)
        ENUM_IMGUI_KEY(F20)
        ENUM_IMGUI_KEY(F21)
        ENUM_IMGUI_KEY(F22)
        ENUM_IMGUI_KEY(F23)
        ENUM_IMGUI_KEY(F24)
        ENUM_IMGUI_KEY(Apostrophe)       
        ENUM_IMGUI_KEY(Comma)            
        ENUM_IMGUI_KEY(Minus)            
        ENUM_IMGUI_KEY(Period)           
        ENUM_IMGUI_KEY(Slash)            
        ENUM_IMGUI_KEY(Semicolon)        
        ENUM_IMGUI_KEY(Equal)            
        ENUM_IMGUI_KEY(LeftBracket)      
        ENUM_IMGUI_KEY(Backslash)       
        ENUM_IMGUI_KEY(RightBracket)     
        ENUM_IMGUI_KEY(GraveAccent)      
        ENUM_IMGUI_KEY(CapsLock)
        ENUM_IMGUI_KEY(ScrollLock)
        ENUM_IMGUI_KEY(NumLock)
        ENUM_IMGUI_KEY(PrintScreen)
        ENUM_IMGUI_KEY(Pause)
        ENUM_IMGUI_KEY(Keypad0) 
        ENUM_IMGUI_KEY(Keypad1) 
        ENUM_IMGUI_KEY(Keypad2) 
        ENUM_IMGUI_KEY(Keypad3) 
        ENUM_IMGUI_KEY(Keypad4)
        ENUM_IMGUI_KEY(Keypad5) 
        ENUM_IMGUI_KEY(Keypad6) 
        ENUM_IMGUI_KEY(Keypad7) 
        ENUM_IMGUI_KEY(Keypad8) 
        ENUM_IMGUI_KEY(Keypad9)
        ENUM_IMGUI_KEY(KeypadDecimal)
        ENUM_IMGUI_KEY(KeypadDivide)
        ENUM_IMGUI_KEY(KeypadMultiply)
        ENUM_IMGUI_KEY(KeypadSubtract)
        ENUM_IMGUI_KEY(KeypadAdd)
        ENUM_IMGUI_KEY(KeypadEnter)
        ENUM_IMGUI_KEY(KeypadEqual)
        ENUM_IMGUI_KEY(AppBack)              
        ENUM_IMGUI_KEY(AppForward)
        ENUM_IMGUI_KEY(Oem102)               
        ENUM_IMGUI_KEY(GamepadStart)          
        ENUM_IMGUI_KEY(GamepadBack)           
        ENUM_IMGUI_KEY(GamepadFaceLeft)       
        ENUM_IMGUI_KEY(GamepadFaceRight)      
        ENUM_IMGUI_KEY(GamepadFaceUp)         
        ENUM_IMGUI_KEY(GamepadFaceDown)       
        ENUM_IMGUI_KEY(GamepadDpadLeft)       
        ENUM_IMGUI_KEY(GamepadDpadRight)      
        ENUM_IMGUI_KEY(GamepadDpadUp)         
        ENUM_IMGUI_KEY(GamepadDpadDown)       
        ENUM_IMGUI_KEY(GamepadL1)             
        ENUM_IMGUI_KEY(GamepadR1)             
        ENUM_IMGUI_KEY(GamepadL2)             
        ENUM_IMGUI_KEY(GamepadR2)             
        ENUM_IMGUI_KEY(GamepadL3)             
        ENUM_IMGUI_KEY(GamepadR3)             
        ENUM_IMGUI_KEY(GamepadLStickLeft)     
        ENUM_IMGUI_KEY(GamepadLStickRight)    
        ENUM_IMGUI_KEY(GamepadLStickUp)       
        ENUM_IMGUI_KEY(GamepadLStickDown)     
        ENUM_IMGUI_KEY(GamepadRStickLeft)     
        ENUM_IMGUI_KEY(GamepadRStickRight)    
        ENUM_IMGUI_KEY(GamepadRStickUp)       
        ENUM_IMGUI_KEY(GamepadRStickDown)     
        ENUM_IMGUI_KEY(MouseLeft)
        ENUM_IMGUI_KEY(MouseRight)
        ENUM_IMGUI_KEY(MouseMiddle)
        ENUM_IMGUI_KEY(MouseX1) 
        ENUM_IMGUI_KEY(MouseX2) 
        ENUM_IMGUI_KEY(MouseWheelX) 
        ENUM_IMGUI_KEY(MouseWheelY)
        .value("Mod_None_",  ImGuiMod_None)
        .value("Mod_Ctrl",  ImGuiMod_Ctrl)
        .value("Mod_Shift", ImGuiMod_Shift)
        .value("Mod_Alt",   ImGuiMod_Alt)
        .value("Mod_Super", ImGuiMod_Super)
        .value("Mod_Mask_", ImGuiMod_Mask_)
        .export_values();
}

void bind_imgui_input_flags(py::module_& m) {
    py::enum_<ImGuiInputFlags_>(m, "InputFlags", py::arithmetic())
        .value("None_", ImGuiInputFlags_None)
        ENUM_IMGUI_INPUT_FLAGS(Repeat)
        ENUM_IMGUI_INPUT_FLAGS(RouteActive)
        ENUM_IMGUI_INPUT_FLAGS(RouteFocused)
        ENUM_IMGUI_INPUT_FLAGS(RouteGlobal)
        ENUM_IMGUI_INPUT_FLAGS(RouteAlways)
        ENUM_IMGUI_INPUT_FLAGS(RouteOverFocused)
        ENUM_IMGUI_INPUT_FLAGS(RouteOverActive)
        ENUM_IMGUI_INPUT_FLAGS(RouteUnlessBgFocused)
        ENUM_IMGUI_INPUT_FLAGS(RouteFromRootWindow)
        ENUM_IMGUI_INPUT_FLAGS(Tooltip)
        .export_values();
}

void bind_imgui_config_flags(py::module_& m) {
    py::enum_<ImGuiConfigFlags_>(m, "ConfigFlags", py::arithmetic())
        .value("None_", ImGuiConfigFlags_None)
        ENUM_IMGUI_CONFIG_FLAGS(NavEnableKeyboard)    
        ENUM_IMGUI_CONFIG_FLAGS(NavEnableGamepad)     
        ENUM_IMGUI_CONFIG_FLAGS(NoMouse)              
        ENUM_IMGUI_CONFIG_FLAGS(NoMouseCursorChange)  
        ENUM_IMGUI_CONFIG_FLAGS(NoKeyboard)           
        .export_values();
}

void bind_imgui_col(py::module_& m) {
    py::enum_<ImGuiCol_>(m, "Col", py::arithmetic())
        ENUM_IMGUI_COL(Text)
        ENUM_IMGUI_COL(TextDisabled)
        ENUM_IMGUI_COL(WindowBg)         
        ENUM_IMGUI_COL(ChildBg)          
        ENUM_IMGUI_COL(PopupBg)               
        ENUM_IMGUI_COL(Border)
        ENUM_IMGUI_COL(BorderShadow)
        ENUM_IMGUI_COL(FrameBg)               
        ENUM_IMGUI_COL(FrameBgHovered)
        ENUM_IMGUI_COL(FrameBgActive)
        ENUM_IMGUI_COL(TitleBg)               
        ENUM_IMGUI_COL(TitleBgActive)         
        ENUM_IMGUI_COL(TitleBgCollapsed)      
        ENUM_IMGUI_COL(MenuBarBg)
        ENUM_IMGUI_COL(ScrollbarBg)
        ENUM_IMGUI_COL(ScrollbarGrab)
        ENUM_IMGUI_COL(ScrollbarGrabHovered)
        ENUM_IMGUI_COL(ScrollbarGrabActive)
        ENUM_IMGUI_COL(CheckMark)            
        ENUM_IMGUI_COL(SliderGrab)
        ENUM_IMGUI_COL(SliderGrabActive)
        ENUM_IMGUI_COL(Button)
        ENUM_IMGUI_COL(ButtonHovered)
        ENUM_IMGUI_COL(ButtonActive)
        ENUM_IMGUI_COL(Header)              
        ENUM_IMGUI_COL(HeaderHovered)
        ENUM_IMGUI_COL(HeaderActive)
        ENUM_IMGUI_COL(Separator)
        ENUM_IMGUI_COL(SeparatorHovered)
        ENUM_IMGUI_COL(SeparatorActive)
        ENUM_IMGUI_COL(ResizeGrip)           
        ENUM_IMGUI_COL(ResizeGripHovered)
        ENUM_IMGUI_COL(ResizeGripActive)
        ENUM_IMGUI_COL(InputTextCursor)      
        ENUM_IMGUI_COL(TabHovered)           
        ENUM_IMGUI_COL(Tab)                  
        ENUM_IMGUI_COL(TabSelected)          
        ENUM_IMGUI_COL(TabSelectedOverline)  
        ENUM_IMGUI_COL(TabDimmed)            
        ENUM_IMGUI_COL(TabDimmedSelected)    
        ENUM_IMGUI_COL(TabDimmedSelectedOverline)
        ENUM_IMGUI_COL(PlotLines)
        ENUM_IMGUI_COL(PlotLinesHovered)
        ENUM_IMGUI_COL(PlotHistogram)
        ENUM_IMGUI_COL(PlotHistogramHovered)
        ENUM_IMGUI_COL(TableHeaderBg)         
        ENUM_IMGUI_COL(TableBorderStrong)     
        ENUM_IMGUI_COL(TableBorderLight)      
        ENUM_IMGUI_COL(TableRowBg)            
        ENUM_IMGUI_COL(TableRowBgAlt)         
        ENUM_IMGUI_COL(TextLink)              
        ENUM_IMGUI_COL(TextSelectedBg)        
        ENUM_IMGUI_COL(TreeLines)             
        ENUM_IMGUI_COL(DragDropTarget)        
        ENUM_IMGUI_COL(NavCursor)             
        ENUM_IMGUI_COL(NavWindowingHighlight) 
        ENUM_IMGUI_COL(NavWindowingDimBg)     
        ENUM_IMGUI_COL(ModalWindowDimBg)      
        .export_values();
}

void bind_imgui_style_var(py::module_& m) {
    py::enum_<ImGuiStyleVar_>(m, "StyleVar", py::arithmetic())
        ENUM_IMGUI_STYLE_VAR(Alpha)                    
        ENUM_IMGUI_STYLE_VAR(DisabledAlpha)            
        ENUM_IMGUI_STYLE_VAR(WindowPadding)            
        ENUM_IMGUI_STYLE_VAR(WindowRounding)           
        ENUM_IMGUI_STYLE_VAR(WindowBorderSize)         
        ENUM_IMGUI_STYLE_VAR(WindowMinSize)            
        ENUM_IMGUI_STYLE_VAR(WindowTitleAlign)         
        ENUM_IMGUI_STYLE_VAR(ChildRounding)            
        ENUM_IMGUI_STYLE_VAR(ChildBorderSize)          
        ENUM_IMGUI_STYLE_VAR(PopupRounding)            
        ENUM_IMGUI_STYLE_VAR(PopupBorderSize)          
        ENUM_IMGUI_STYLE_VAR(FramePadding)             
        ENUM_IMGUI_STYLE_VAR(FrameRounding)            
        ENUM_IMGUI_STYLE_VAR(FrameBorderSize)          
        ENUM_IMGUI_STYLE_VAR(ItemSpacing)              
        ENUM_IMGUI_STYLE_VAR(ItemInnerSpacing)         
        ENUM_IMGUI_STYLE_VAR(IndentSpacing)            
        ENUM_IMGUI_STYLE_VAR(CellPadding)              
        ENUM_IMGUI_STYLE_VAR(ScrollbarSize)            
        ENUM_IMGUI_STYLE_VAR(ScrollbarRounding)        
        ENUM_IMGUI_STYLE_VAR(GrabMinSize)              
        ENUM_IMGUI_STYLE_VAR(GrabRounding)             
        ENUM_IMGUI_STYLE_VAR(ImageBorderSize)          
        ENUM_IMGUI_STYLE_VAR(TabRounding)              
        ENUM_IMGUI_STYLE_VAR(TabBorderSize)            
        ENUM_IMGUI_STYLE_VAR(TabBarBorderSize)         
        ENUM_IMGUI_STYLE_VAR(TabBarOverlineSize)       
        ENUM_IMGUI_STYLE_VAR(TableAngledHeadersAngle)  
        ENUM_IMGUI_STYLE_VAR(TableAngledHeadersTextAlign)
        ENUM_IMGUI_STYLE_VAR(TreeLinesSize)            
        ENUM_IMGUI_STYLE_VAR(TreeLinesRounding)        
        ENUM_IMGUI_STYLE_VAR(ButtonTextAlign)          
        ENUM_IMGUI_STYLE_VAR(SelectableTextAlign)      
        ENUM_IMGUI_STYLE_VAR(SeparatorTextBorderSize)  
        ENUM_IMGUI_STYLE_VAR(SeparatorTextAlign)       
        ENUM_IMGUI_STYLE_VAR(SeparatorTextPadding)     
        .export_values();
}

void bind_imgui_button_flags(py::module_& m) {
    py::enum_<ImGuiButtonFlags_>(m, "ButtonFlags", py::arithmetic())
        .value("None_", ImGuiButtonFlags_None)
        ENUM_IMGUI_BUTTON_FLAGS(MouseButtonLeft)
        ENUM_IMGUI_BUTTON_FLAGS(MouseButtonRight)
        ENUM_IMGUI_BUTTON_FLAGS(MouseButtonMiddle)
        ENUM_IMGUI_BUTTON_FLAGS(MouseButtonMask_)
        ENUM_IMGUI_BUTTON_FLAGS(EnableNav)
        .export_values();
}

void bind_imgui_color_edit_flags(py::module_& m) {
    py::enum_<ImGuiColorEditFlags_>(m, "ColorEditFlags", py::arithmetic())
        .value("None_", ImGuiColorEditFlags_None)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoAlpha)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoPicker)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoOptions)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoSmallPreview)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoInputs)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoTooltip)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoLabel)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoSidePreview)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoDragDrop)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(NoBorder)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(AlphaOpaque)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(AlphaNoBg)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(AlphaPreviewHalf)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(AlphaBar)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(HDR)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DisplayRGB)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DisplayHSV)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DisplayHex)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(Uint8)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(Float)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(PickerHueBar)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(PickerHueWheel)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(InputRGB)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(InputHSV)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DefaultOptions_)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(AlphaMask_)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DisplayMask_)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(DataTypeMask_)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(PickerMask_)
        ENUM_IMGUI_COLOR_EDIT_FLAGS(InputMask_)
        .export_values();
}

void bind_imgui_slider_flags(py::module_& m) {
    py::enum_<ImGuiSliderFlags_>(m, "SliderFlags", py::arithmetic())
        .value("None_", ImGuiSliderFlags_None)
        ENUM_IMGUI_SLIDER_FLAGS(Logarithmic)
        ENUM_IMGUI_SLIDER_FLAGS(NoRoundToFormat)
        ENUM_IMGUI_SLIDER_FLAGS(NoInput)
        ENUM_IMGUI_SLIDER_FLAGS(WrapAround)
        ENUM_IMGUI_SLIDER_FLAGS(ClampOnInput)
        ENUM_IMGUI_SLIDER_FLAGS(ClampZeroRange)
        ENUM_IMGUI_SLIDER_FLAGS(NoSpeedTweaks)
        ENUM_IMGUI_SLIDER_FLAGS(AlwaysClamp)
        ENUM_IMGUI_SLIDER_FLAGS(InvalidMask_)
        .export_values();
}

void bind_imgui_mouse_button(py::module_& m) {
    py::enum_<ImGuiMouseButton_>(m, "MouseButton", py::arithmetic())
        ENUM_IMGUI_MOUSE_BUTTON(Left)
        ENUM_IMGUI_MOUSE_BUTTON(Right)
        ENUM_IMGUI_MOUSE_BUTTON(Middle)
        .export_values();
}

void bind_imgui_mouse_cursor(py::module_& m) {
    py::enum_<ImGuiMouseCursor_>(m, "MouseCursor", py::arithmetic())
        .value("None_", ImGuiMouseCursor_None)
        ENUM_IMGUI_MOUSE_CURSOR(Arrow)
        ENUM_IMGUI_MOUSE_CURSOR(TextInput)       
        ENUM_IMGUI_MOUSE_CURSOR(ResizeAll)       
        ENUM_IMGUI_MOUSE_CURSOR(ResizeNS)        
        ENUM_IMGUI_MOUSE_CURSOR(ResizeEW)        
        ENUM_IMGUI_MOUSE_CURSOR(ResizeNESW)      
        ENUM_IMGUI_MOUSE_CURSOR(ResizeNWSE)      
        ENUM_IMGUI_MOUSE_CURSOR(Hand)            
        ENUM_IMGUI_MOUSE_CURSOR(Wait)            
        ENUM_IMGUI_MOUSE_CURSOR(Progress)        
        ENUM_IMGUI_MOUSE_CURSOR(NotAllowed)      
        .export_values();
}

void bind_imgui_cond(py::module_& m) {
    py::enum_<ImGuiCond_>(m, "Cond", py::arithmetic())
        .value("None_", ImGuiCond_None)
        ENUM_IMGUI_COND(Always)
        ENUM_IMGUI_COND(Once)
        ENUM_IMGUI_COND(FirstUseEver)
        ENUM_IMGUI_COND(Appearing)
        .export_values();
}

void bind_imgui_table_flags(py::module_& m) {
    py::enum_<ImGuiTableFlags_>(m, "TableFlags", py::arithmetic())
        .value("None_", ImGuiTableFlags_None)
        ENUM_IMGUI_TABLE_FLAGS(Resizable)
        ENUM_IMGUI_TABLE_FLAGS(Reorderable)
        ENUM_IMGUI_TABLE_FLAGS(Hideable)
        ENUM_IMGUI_TABLE_FLAGS(Sortable)
        ENUM_IMGUI_TABLE_FLAGS(NoSavedSettings)
        ENUM_IMGUI_TABLE_FLAGS(ContextMenuInBody)
        ENUM_IMGUI_TABLE_FLAGS(RowBg)
        ENUM_IMGUI_TABLE_FLAGS(BordersInnerH)
        ENUM_IMGUI_TABLE_FLAGS(BordersOuterH)
        ENUM_IMGUI_TABLE_FLAGS(BordersInnerV)
        ENUM_IMGUI_TABLE_FLAGS(BordersOuterV)
        ENUM_IMGUI_TABLE_FLAGS(BordersH)
        ENUM_IMGUI_TABLE_FLAGS(BordersV)
        ENUM_IMGUI_TABLE_FLAGS(BordersInner)
        ENUM_IMGUI_TABLE_FLAGS(BordersOuter)
        ENUM_IMGUI_TABLE_FLAGS(Borders)
        ENUM_IMGUI_TABLE_FLAGS(NoBordersInBody)
        ENUM_IMGUI_TABLE_FLAGS(NoBordersInBodyUntilResize)
        ENUM_IMGUI_TABLE_FLAGS(SizingFixedFit)
        ENUM_IMGUI_TABLE_FLAGS(SizingFixedSame)
        ENUM_IMGUI_TABLE_FLAGS(SizingStretchProp)
        ENUM_IMGUI_TABLE_FLAGS(SizingStretchSame)
        ENUM_IMGUI_TABLE_FLAGS(NoHostExtendX)
        ENUM_IMGUI_TABLE_FLAGS(NoHostExtendY)
        ENUM_IMGUI_TABLE_FLAGS(NoKeepColumnsVisible)
        ENUM_IMGUI_TABLE_FLAGS(PreciseWidths)
        ENUM_IMGUI_TABLE_FLAGS(NoClip)
        ENUM_IMGUI_TABLE_FLAGS(PadOuterX)
        ENUM_IMGUI_TABLE_FLAGS(NoPadOuterX)
        ENUM_IMGUI_TABLE_FLAGS(NoPadInnerX)
        ENUM_IMGUI_TABLE_FLAGS(ScrollX)
        ENUM_IMGUI_TABLE_FLAGS(ScrollY)
        ENUM_IMGUI_TABLE_FLAGS(SortMulti)
        ENUM_IMGUI_TABLE_FLAGS(SortTristate)
        ENUM_IMGUI_TABLE_FLAGS(HighlightHoveredColumn)
        .export_values();
}

void bind_imgui_table_coloumn_flags(py::module_& m) {
    py::enum_<ImGuiTableColumnFlags_>(m, "TableColumnFlags", py::arithmetic())
        .value("None_", ImGuiTableColumnFlags_None)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(Disabled)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(DefaultHide)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(DefaultSort)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(WidthStretch)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(WidthFixed)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoResize)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoReorder)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoHide)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoClip)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoSort)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoSortAscending)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoSortDescending)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoHeaderLabel)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(NoHeaderWidth)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(PreferSortAscending)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(PreferSortDescending)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IndentEnable)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IndentDisable)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(AngledHeader)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IsEnabled)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IsVisible)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IsSorted)
        ENUM_IMGUI_TABLE_COLUMN_FLAGS(IsHovered)
        .export_values();
}

void bind_imgui_table_row_flags(py::module_& m) {
    py::enum_<ImGuiTableRowFlags_>(m, "TableRowFlags", py::arithmetic())
        .value("None_", ImGuiTableRowFlags_None)
        ENUM_IMGUI_TABLE_ROW_FLAGS(Headers)
        .export_values();
}

void bind_imgui_table_bg_target(py::module_& m) {
    py::enum_<ImGuiTableBgTarget_>(m, "TableBgTarget", py::arithmetic())
        .value("None_", ImGuiTableBgTarget_None)
        ENUM_IMGUI_TABLE_BG_TARGET(RowBg0)
        ENUM_IMGUI_TABLE_BG_TARGET(RowBg1)
        ENUM_IMGUI_TABLE_BG_TARGET(CellBg)
        .export_values();
}

void bind_imgui_multi_select_flags(py::module_& m) {
    py::enum_<ImGuiMultiSelectFlags_>(m, "MultiSelectFlags", py::arithmetic())
        .value("None_", ImGuiMultiSelectFlags_None)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(SingleSelect)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(NoSelectAll)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(NoRangeSelect)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(NoAutoSelect)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(NoAutoClear)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(NoAutoClearOnReselect)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(BoxSelect1d)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(BoxSelect2d)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(BoxSelectNoScroll)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(ClearOnEscape)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(ClearOnClickVoid)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(ScopeWindow)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(ScopeRect)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(SelectOnClick)
        ENUM_IMGUI_MULTI_SELECT_FLAGS(SelectOnClickRelease)
        .export_values();
}

void bind_imgui_selection_request_type(py::module_& m) {
    py::enum_<ImGuiSelectionRequestType>(m, "SelectionRequestType", py::arithmetic())
        .value("None_", ImGuiSelectionRequestType_None)
        ENUM_IMGUI_SELECTION_REQUEST_TYPE(SetAll)
        ENUM_IMGUI_SELECTION_REQUEST_TYPE(SetRange)
        .export_values();
}

void bind_imgui_draw_flags(py::module_& m) {
    py::enum_<ImDrawFlags_>(m, "DrawFlags", py::arithmetic())
        .value("None_", ImDrawFlags_None)
        ENUM_IMGUI_DRAW_FLAGS(Closed)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersTopLeft)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersTopRight)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersBottomLeft)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersBottomRight)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersNone)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersTop)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersBottom)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersLeft)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersRight)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersAll)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersDefault_)
        ENUM_IMGUI_DRAW_FLAGS(RoundCornersMask_)
        .export_values();
}

void bind_imgui_draw_list_flags(py::module_& m) {
    py::enum_<ImDrawListFlags_>(m, "DrawListFlags", py::arithmetic())
        .value("None_", ImDrawListFlags_None)
        ENUM_IMGUI_DRAW_LIST_FLAGS(AntiAliasedLines)
        ENUM_IMGUI_DRAW_LIST_FLAGS(AntiAliasedLinesUseTex)
        ENUM_IMGUI_DRAW_LIST_FLAGS(AntiAliasedFill)
        ENUM_IMGUI_DRAW_LIST_FLAGS(AllowVtxOffset)
        .export_values();
}

void bind_imgui_font_atlas_flags(py::module_& m) {
    py::enum_<ImFontAtlasFlags_>(m, "FontAtlasFlags", py::arithmetic())
        .value("None_", ImFontAtlasFlags_None)
        ENUM_IMGUI_FONT_ATLAS_FLAGS(NoPowerOfTwoHeight)
        ENUM_IMGUI_FONT_ATLAS_FLAGS(NoMouseCursors)
        ENUM_IMGUI_FONT_ATLAS_FLAGS(NoBakedLines)
        .export_values();
}
